name: Run the tests, Build the image

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.11
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Unit Testing
          run: |
            docker login --username ramosjaa --password ${{secrets.ACCESS_TOKEN}} ghcr.io
            docker build -t ghcr.io/ramosjaa/cipher-service:latest --file Dockerfile .
            docker push ghcr.io/ramosjaa/cipher-service:latest